### PR TITLE
Proper __GLASGOW_HASKELL__ value

### PR DESCRIPTION
**Pull request by pmlodawski**
`__GLASGOW_HASKELL__>= 702` instead of `__GLASGOW_HASKELL__ >= 720`

### CODE REVIEW

**Comment by ivan-m** [comment]
This seems to break on 7.4.2 based upon the results from Travis CI... this looks like it's a problem with the .cabal file settings as it says it can't find ghc-prim.

**Comment by ivan-m** [comment]
OK, I fixed the problem and merged this (GitHub can't detect that, I think because the hash changed to 6de9ae5).

**Comment by pmlodawski** [comment]
Thanks a lot!

**Comment by pmlodawski** [comment]
When are you planning new hackage release?

**Comment by ivan-m** [comment]
I'm trying to get the test-suite finished first, and am waiting for pull requests to get cleaned up.

So... hopefully soon? :p

**Comment by pmlodawski** [comment]
I think it will take a while, but I keep my fingers crossed ;)

**Pull request closed without merging**
