### PR TITLE
Gr deriving Generic

### PR DESCRIPTION
**Pull request by pmlodawski**
Hello! I made Gr deriving Generic, which make possible to make other standalone derivings for graphs, e.g. deriving Binary

### CODE REVIEW

**Comment by ivan-m** [comment]
My only qualm with this is that I'm trying to keep FGL working on old versions of GHC just in case as much as possible, but DeriveGeneric requires >= 7.2.  I'll have to think about this.

**Comment by pmlodawski** [comment]
Everything now is in single commit

**Comment by pmlodawski** [comment]
Backward compability with so old GHC's is fine, but I think binary serialization of graphs is important feature too. We can also make deriving Generic inside if clause, only for newer GHC...

**Comment by ivan-m** [comment]
Actually, if you can use CPP to do an ifdef around it, then that should suffice and I'll merge it.

**Comment by pmlodawski** [comment]
I wrapped it in ifdefs, but unfortuantely I cannot squash it into single commit this time...

**Comment by ivan-m** [comment]
I think the usage of `ghc-prim` in the .cabal file needs to only happen for >= 7.2 as well.

Why can't you squash the commits?

**Comment by hvr** [comment]
@ivan-m actually, if `ghc-prim` is only needed for `GHC.Generics`, you only need it for 7.2 and 7.4;
c.f. http://hackage.haskell.org/package/deepseq-1.4.1.1/deepseq.cabal

**Comment by ivan-m** [comment]
@hvr that's what I meant (as it already has <7.6 in the .cabal file).

**Comment by pmlodawski** [comment]
I changed ghc-prim dependency to `ghc >= 7.2 && ghc <= 7.4`

**Comment by ivan-m** [comment]
Applied, thanks!

**Comment by pmlodawski** [comment]
Cool, thanks!

**Comment by pmlodawski** [comment]
Aww, looks like ghc-7.2 generates `__GLASGOW_HASKELL__ == 702`, not `720`...Just noticed it.. sorry. I'll make another pull request with this fixed ;/

**Pull request merged**
