### PR TITLE
Add toMap function to convert a NodeMap into an ordinary Data.Map

### PR DESCRIPTION
**Pull request by carlostome**
I added a function to unwrap the NodeMap into Haskell's Data.Map so it can be used outsided the graph.

### CODE REVIEW

**Comment by ivan-m** [comment]
Do you have a use-case for this?  To me, this sounds like it might be exposing an internal representation.

That said, a better representation would be `toMap = map` (as `map` is the internal field selector function).

**Comment by ivan-m** [comment]
@carlostome do you have an actual use case for this?  If not, I'll close this pull request.

**Comment by ivan-m** [comment]
@carlostome If you'd like this in the next (and hopefully soon!) release, please re-open this pull request.

**Comment by ciez** [comment]
here is a use case: 

a test of graph serialization does this:
create a dummy graph g1 with a few nodes and edges using 
`run g insMapNodesM a`
serialize this graph to ByteString, deserialize it back to g2

run a few queries to compare g1 and g2
some queries need Node. To look up Node from label, mkNode_ may be used.

2 issues when using mkNode_:
1) it is necessary to additionally test if the node exists in the graph e.g. using gelem
2) test failed because of a non-terminated loop 

after exposing NodeMap's internal map and looking up Node directly from this exposed map, 2) is resolved and the test passes. No other changes to the test were necessary. I guess there is some caveat with using mkNode_ in this test.

generally, a -> Node is probably a very common op. Why not expose the map and save users a few hours each?

**Pull request closed without merging**
