### PR TITLE
Add condensation.

### PR DESCRIPTION
**Pull request by scolobb**
This pull request adds the function for computing the condensation a graph: the graph of its strongly connected components.

### CODE REVIEW

**Comment by gregorycollins** [comment]
Could you please add some tests for the new functions?

**Comment by ivan-m** [comment]
@gregorycollins actually, I need to work out a proper test suite for fgl as it is; currently it's just a bunch of values (I think to have values to _let_ you test with rather than actual tests for the library).

**Comment by ivan-m** [comment]
See #5.

**Comment by scolobb** [comment]
Hello!  Sorry for the big delay -- I had some unpleasant deadlines.  I should normally be able to react in under a week.

I squashed the commits, as suggested. I also added the undirected adjacency functions. I'm not sure we have the same vision of what they should do, so I am open to suggestions for improvements.

**Comment by scolobb** [comment]
I use `toLEdge` in `condensation` now.

I gave in to the cleaning-up spree and also rewrote the `if` in the construction of `es` to rely on `fail` in the list monad.  I can revert it back to an `if` if you find that more appropriate.

**Comment by ivan-m** [comment]
Please rebase this on current version of master; in particular, I dropped the big block of type-signature comments so you can remove those from the relevant commits.

I'm also going to migrate the old tests over to the new hspec-based test suite, so once I've done that please re-write your tests to use that as well.

**Comment by scolobb** [comment]
I rebased the branch and updated `context14l` to use `mcontext`.

I noticed that there is a (new?) function `neighbors` which does the same thing as my `undirAdj`. Do you want me to drop `undirAdj`? If yes, I could also rename `undirLAdj` to something like `neighborsLAdj`.

I'll also try to keep an eye on the new test suite.

**Comment by ivan-m** [comment]
Well, I certainly didn't add `neighbours` (it's missing a "u"! :p).

But I can add a `lneighbours` function (similar naming scheme as with `lsuc`, etc.).  This will return `[(Node,b)]`; is that OK?

(In which case, we then have `neighbours = map fst .: lneighbours`.)

Though what happened to your changes to DFS?  I thought you had removed usage of `Data.Tuple(swap)` (for backwards-compatibility with older GHC's) and swung the contents of the where clause down :s

**Comment by scolobb** [comment]
Yeah, `lneighbours` seems nice. I can even add it myself and rewrite `neighbours` (which does appear without a 'u' when I look into the current master ;-) ).

As for DFS, it seems that I just forgot to remove that import :-/

**Comment by ivan-m** [comment]
Yeah, it shouldn't have the `u`; I just keep typing it that way because I was raised to write with the Queen's English but Martin Erwig obviously wasn't :p

**Comment by scolobb** [comment]
OK, I fixed DFS according to your suggestions. I'll take care of the neighboUrs a bit later. (Yeah, I like keeping u's as well, but probably for less serious reasons than you :-) )

**Comment by ivan-m** [comment]
Have a look at the [query-tests](https://github.com/haskell/fgl/tree/query-tests) branch to get an idea of how to add tests.

I would prefer QuickCheck-based tests, but using unit tests with hspec are also fine.

**Comment by ivan-m** [comment]
Actually, I'm finding myself needing something along the lines of your `hasUndirEdge` (whatever we end up calling it) for some tests; any chance you'll be able to get at least the first few commits re-done so I can merge them (even if you add the test one afterwards)?

**Comment by scolobb** [comment]
Aand I'm back again :-) I'm going to fix everything except the tests right away.

**Comment by scolobb** [comment]
All right, I removed `undir(L)Adj` and added `neighbors'` and `lneighbors'` instead. I changed `hasUndirEdge` to `hasNeighbor`, as you suggested, and `hasUndirLEdge` to `hasNeighborAdj`, because the type `Adj` is used to describe labelled links, and we are looking for a labelled link to a neighbour (yeah, not a particularly solid motivation :-) ).  I also rewrote `condensation` according to your suggestions (thanks, by the way, all these advices are quite enlightening!)

`lneighbors` and `lneighbors'` return `Adj b` in this version, instead of `[(Node, b)]`. I can see that `lsuc`, for example, prefers the second type to the first. Why is that? If that's necessary, I can change the neighbours-related functions to return `[(Node,b)]` as well.

**Comment by scolobb** [comment]
I'll look into the tests soon. I will then take care of my other pull request. Sorry for bad latency, I'm still in a kind of a deadliney season.

**Comment by ivan-m** [comment]
I have no idea why `lsuc`, etc. return `[(Node, b)]` rather than `Adj b`; possibly to make it `Node`-centric (though it could be argued that `Adj` is the wrong way round).

Please do an interactive rebase to change the order of commits: `hasNeighborAdj` depends upon `lneighbors` You might as well also make `neighbors = map snd .: lneighbors` in that commit.

Once that's done I'll merge in the first three commits and leave the test one for now.

**Comment by scolobb** [comment]
I changed `neighbors' to use `lneigbors`.

I have no idea why the commits used to be shown in that order -- I always had the one adding `neighbors` before the one adding the edge functions.

I started looking into QuickCheck yesterday, so, hopefully, the tests will follow more or less soon, especially given that you have already added lots of stuff to `fgl-arbitrary` and I seem to only have to formulate the invariants, which I kind of have already.

**Comment by scolobb** [comment]
OK, I am finally getting back to work on my pull requests. I will first check out the recent developments and will then try to add the tests.

**Comment by scolobb** [comment]
I added a QuickCheck test for `condensation`.  I saw that you did not add any explicit tests for simple functions similar to `hasEdge`, so I didn't add any tests for `hasEdge`, `hasLEdge`, `hasNeighbor`, `hasNeighborAdj`, `lneighbors`, and `lneighbors`.  Do you think it would be desirable to test them too?

**Comment by scolobb** [comment]
And no, I still have no idea about why GitHub would show the commits in the wrong order. I see them like this: https://github.com/scolobb/fgl/commits/condensation .

**Comment by ivan-m** [comment]
Probably should have tests those functions, but I couldn't think of any that were interesting enough that weren't already covered by one of the functions that they use.

I think that the first two commits can be squashed together (and the commit message just something like "Additional edge- and neighbor-based functions"), and the condensation test squashed with its implementation.

I think the weird ordering is because when you squash commits it keeps the original timestamp (if you look through my commit history you'll see it looks like a time machine :p).

**Comment by scolobb** [comment]
I believe I've fixed everything according to your suggestions.

> Probably should have tests those functions, but I couldn't think of any that were interesting enough that weren't already covered by one of the functions that they use.

Well, I added test for `hasNeighbor`, `hasNeighborAdj`, as well as `hasLEdge`.  This seems to cover the whole chain of neighbour-related functions, and `hasEdge` is already used in so many test cases that it doesn't seem to need any more explicit testing.

> I think the weird ordering is because when you squash commits it keeps the original timestamp (if you look through my commit history you'll see it looks like a time machine :p).

Aah, yeah, probably.  You're a rebase ninja then :-) I was expecting GitHub to show the commits in the order they are stacked in the branch rather than according to timestamps.  Preferring the latter seems a rather peculiar choice.

**Comment by scolobb** [comment]
OK, I am surprised.  I cannot reliably reproduce this failure.  By running the test suite a dozen times I found that, for example, seeds 1460445423 and 1252746575 fail on my machine.

I immediately tried making `hasNeighbor` and `hasNeighborAdj` check if `v` is a neighbour of `w` _or_ if `w` is a neighbour of `v` (right now only one of the conditions is checked), but it doesn't seem to fix the issue :-(

Let me try to get some sleep and see if that helps.

**Comment by ivan-m** [comment]
I know the problem.

If you have an edge `(v,w)` in the graph but _not_ `(w,v)` and try the test with the latter, then it will fail because the LHS is False but the RHS is True.

Two possible solutions:

* use the Undirected wrapper from `Data.Graph.Inductive.Arbitrary` (see the `Query` properties for examples)

* replace the LHS with testing for either `(v,w)` _or_ `(w,v)` being in the graph.  Especially if taking this route, I would change the test to taking in two `Node` values rather than an `Edge`.  (Rather than using `elem`, I think `any` might be more appropriate for this).

Whichever route you take (I think the latter is preferable), apply it to all the neighbor-based tests.

**Comment by scolobb** [comment]
Oh, sure, I felt something was wrong with my test conditions, but I was blind enough to overlook this :-D Here's the update.

**Comment by ivan-m** [comment]
Can you please make a new pull-request renaming your tests to use the `valid_` prefix rather than `test_` to be consistent? (I missed that before.)

I can do it if you prefer; I just figured that you might as well keep ownership of your part of the library :)

**Pull request merged**
