### PR TITLE
Add documentation to SP.hs, DFS.hs

### PR DESCRIPTION
**Pull request by quchen**
The documentation of most modules is a bit lacking, so I decided to add some to SP.hs and DFS.hs.

### CODE REVIEW

**Comment by quchen** [comment]
Alright, will do!

I too think that indenting `-- |` blocks to make the first char each column align looks nicer, but I stopped doing that when I realized it doesn't pair well with `@...@` *multiline* blocks, because those will appear indented in the generated docs.

That's just to explain the rationale, I'll implement your suggestions in due time.

**Comment by ivan-m** [comment]
These commits look good; can you please squash the cosmetic ones back into the original please?

Also, during your documentation of these two modules, have you come up with any viable ideas for tests?

**Comment by ivan-m** [comment]
Hi @quchen,

I'm wanting to make a release of FGL soon (finally!); can you please squash your cosmetic commits back into the original ones?

**Comment by quchen** [comment]
Done

**Comment by ivan-m** [comment]
Applied; thanks!

**Pull request closed without merging**
